// apps/api/src/modules/intelligence/referenceLibrary.ts
// ─────────────────────────────────────────────────────────────────────────────
// Institutional Reference Library
// Machine-readable portfolio intelligence modeling structural patterns,
// content priorities, and design characteristics across major industry standards.
// ─────────────────────────────────────────────────────────────────────────────

import { ReferenceProfile, db } from '../../database/index.js'

export const SEED_REFERENCE_PROFILES: ReferenceProfile[] = [
  {
    id: 'ref-academic-cs',
    name: 'CS Research Fellow & Postdoc',
    institutionArchetype: 'Leading Computer Science Research Institute (e.g. CSAIL / Stanford-style)',
    category: 'Academic',
    profileType: 'Academic Researcher & Systems Theorist',
    description:
      'Prioritizes peer-reviewed publications, research agendas, laboratory grants, and formal computer science education over commercial product marketing.',
    sectionStructure: [
      'Hero',
      'About & Bio',
      'Research Themes',
      'Selected Publications',
      'Funded Projects & Artifacts',
      'Academic Service & Teaching',
      'Education',
      'Contact',
    ],
    contentPriorities: {
      research: 0.95,
      publications: 0.95,
      projects: 0.75,
      education: 0.85,
      experience: 0.7,
      skills: 0.6,
    },
    designCharacteristics: {
      minimalismScore: 0.9,
      contentDensity: 0.85,
      technicalDepth: 0.95,
      visualEmphasis: 0.3,
      navigationStyle: 'minimal-dossier',
    },
    recommendedFor: 'Developers with academic publications, PhD/MS work, research preprints, or formal algorithm innovations.',
    tags: ['research', 'academic', 'publications', 'algorithms', 'peer-review'],
  },
  {
    id: 'ref-sec-cert',
    name: 'High-Assurance Security Researcher',
    institutionArchetype: 'National Vulnerability Research / Offensive-Defensive Security Lab',
    category: 'Cybersecurity',
    profileType: 'Cybersecurity & Exploit/Defensive Specialist',
    description:
      'Emphasizes zero-trust verifiable code artifacts, CVE advisories, cryptography implementations, CTF performance, and audited security toolkits.',
    sectionStructure: [
      'Hero & Threat Model Status',
      'Security Advisories & Research',
      'Verified Security Artifacts',
      'Cryptographic & Systems Tooling',
      'Skill Evidence Matrix',
      'Certifications & Lab Audits',
      'Contact',
    ],
    contentPriorities: {
      research: 0.85,
      projects: 0.9,
      skills: 0.95,
      experience: 0.8,
      education: 0.65,
      publications: 0.7,
      securityAdvisories: 0.95,
      certifications: 0.85,
    },
    designCharacteristics: {
      minimalismScore: 0.85,
      contentDensity: 0.9,
      technicalDepth: 0.95,
      visualEmphasis: 0.4,
      navigationStyle: 'tabbed-telemetry',
    },
    recommendedFor: 'Developers working on cryptography, application security, static analysis, fuzzers, or infrastructure protection.',
    tags: ['cybersecurity', 'cryptography', 'security', 'cve', 'telemetry', 'rust', 'go'],
  },
  {
    id: 'ref-eng-faang',
    name: 'Staff Software Architect',
    institutionArchetype: 'Tier-1 Silicon Valley Engineering Standard (e.g. Distributed Systems Group)',
    category: 'Software Engineering',
    profileType: 'High-Scale Systems & Platform Architect',
    description:
      'Focuses on high-throughput microservices, architectural diagrams, measurable throughput/latency metrics, and production-tested open-source code.',
    sectionStructure: [
      'Hero',
      'Architectural Impact & Summary',
      'Featured High-Scale Projects',
      'Proven Technical Stack',
      'Engineering Career Timeline',
      'Patents & Technical Awards',
      'Contact',
    ],
    contentPriorities: {
      projects: 0.95,
      experience: 0.9,
      skills: 0.85,
      research: 0.5,
      education: 0.65,
      publications: 0.55,
    },
    designCharacteristics: {
      minimalismScore: 0.8,
      contentDensity: 0.75,
      technicalDepth: 0.85,
      visualEmphasis: 0.5,
      navigationStyle: 'single-page-scroll',
    },
    recommendedFor: 'Full-stack and backend developers with high-cadence production projects, high RQS scores, and strong test coverage.',
    tags: ['software-engineering', 'architecture', 'distributed-systems', 'testing', 'scale'],
  },
  {
    id: 'ref-oss-core',
    name: 'Open Source Core Maintainer',
    institutionArchetype: 'Global Open-Source Foundation (e.g. CNCF / Apache / Linux Foundation)',
    category: 'Open Source',
    profileType: 'Ecosystem Maintainer & Library Author',
    description:
      'Highlights contributor velocity, package download telemetry, reproducible lockfiles, multi-architecture CI builds, and community releases.',
    sectionStructure: [
      'Hero & Ecosystem Stats',
      'Maintained Packages & Repositories',
      'Release Cadence & Commit Velocity',
      'Ecosystem Dependencies & Citations',
      'Sponsorship & Community Leadership',
      'Contact',
    ],
    contentPriorities: {
      projects: 0.95,
      skills: 0.85,
      experience: 0.75,
      research: 0.45,
      education: 0.5,
      publications: 0.4,
    },
    designCharacteristics: {
      minimalismScore: 0.75,
      contentDensity: 0.8,
      technicalDepth: 0.85,
      visualEmphasis: 0.55,
      navigationStyle: 'single-page-scroll',
    },
    recommendedFor: 'Developers whose GitHub presence features actively maintained libraries, multiple stargazers, and rigorous CI/CD workflows.',
    tags: ['open-source', 'maintainer', 'github-cadence', 'ci-cd', 'package-releases'],
  },
  {
    id: 'ref-cloud-infra',
    name: 'Cloud Infrastructure & SRE Specialist',
    institutionArchetype: 'Enterprise Cloud Platform Engineering Standard',
    category: 'Systems & Infrastructure',
    profileType: 'Reliability & Cloud Systems Engineer',
    description:
      'Centers on Docker/Kubernetes container definitions, automated IaC workflows, high availability topologies, and system telemetry.',
    sectionStructure: [
      'Hero & Reliability Overview',
      'Infrastructure & Systems Projects',
      'Verified DevOps & Cloud Tooling',
      'CI/CD Workflows & Automation',
      'Incidents & Operational Achievements',
      'Certifications',
      'Contact',
    ],
    contentPriorities: {
      projects: 0.9,
      skills: 0.95,
      experience: 0.85,
      research: 0.4,
      education: 0.6,
      publications: 0.35,
      certifications: 0.8,
    },
    designCharacteristics: {
      minimalismScore: 0.8,
      contentDensity: 0.85,
      technicalDepth: 0.9,
      visualEmphasis: 0.45,
      navigationStyle: 'single-page-scroll',
    },
    recommendedFor: 'Engineers whose repositories contain Dockerfiles, docker-compose manifests, GitHub Actions pipelines, and Kubernetes YAML.',
    tags: ['infrastructure', 'devops', 'docker', 'ci-cd', 'sre', 'cloud'],
  },
  {
    id: 'ref-creative-tech',
    name: 'Creative Technologist & UI Systems Engineer',
    institutionArchetype: 'Interactive Design & Media Laboratory (e.g. Media Lab standard)',
    category: 'Creative Technologist',
    profileType: 'Front-End Craftsman & Interaction Designer',
    description:
      'Balances technical execution with interactive aesthetics, design systems, micro-interactions, responsive typography, and creative computing.',
    sectionStructure: [
      'Hero & Visual Statement',
      'Interactive Work & Case Studies',
      'Design System Components & Demos',
      'Technical Stack & Creative Tools',
      'Exhibitions & Features',
      'Experience & Collabs',
      'Contact',
    ],
    contentPriorities: {
      projects: 0.95,
      skills: 0.8,
      experience: 0.75,
      education: 0.65,
      research: 0.5,
      publications: 0.4,
    },
    designCharacteristics: {
      minimalismScore: 0.65,
      contentDensity: 0.6,
      technicalDepth: 0.7,
      visualEmphasis: 0.9,
      navigationStyle: 'single-page-scroll',
    },
    recommendedFor: 'Frontend developers, UI/UX engineers, and creative coders with rich client-side animations and component libraries.',
    tags: ['creative', 'ui-ux', 'frontend', 'design-systems', 'react', 'visual'],
  },
  {
    id: 'ref-applied-ai',
    name: 'Applied AI & ML Systems Researcher',
    institutionArchetype: 'Frontier AI Research Laboratory (e.g. DeepMind / FAIR archetype)',
    category: 'AI & Machine Learning',
    profileType: 'Machine Learning Engineer & Modeler',
    description:
      'Focuses on empirical evaluation benchmarks, model weights/checkpoints, training pipelines, dataset curation, and reproducible code notebooks.',
    sectionStructure: [
      'Hero',
      'Research Agenda & Model Demos',
      'Benchmark Evaluations & Repos',
      'Preprints & Technical Reports',
      'Compute & Framework Tooling',
      'Education',
      'Contact',
    ],
    contentPriorities: {
      research: 0.9,
      projects: 0.9,
      publications: 0.85,
      skills: 0.8,
      education: 0.8,
      experience: 0.75,
    },
    designCharacteristics: {
      minimalismScore: 0.85,
      contentDensity: 0.8,
      technicalDepth: 0.9,
      visualEmphasis: 0.5,
      navigationStyle: 'minimal-dossier',
    },
    recommendedFor: 'Engineers building neural network architectures, data pipelines, model inference servers, or scientific Python packages.',
    tags: ['ai', 'machine-learning', 'python', 'benchmarks', 'datasets', 'neural-networks'],
  },
]

export function initializeReferenceLibrary(): void {
  for (const ref of SEED_REFERENCE_PROFILES) {
    db.saveReferenceProfile(ref)
  }
}
